apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    api: lease-a-car-api
    service: interest-rate-service
  name: interest-rate-service
  namespace: {{.Values.metadata.namespace}}
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      service: interest-rate-service
  template:
    metadata:
      labels:
        api: lease-a-car-api
        service: interest-rate-service
    spec:
      restartPolicy: Always
      containers:
      - image: {{.Values.image.repository}}/interest-rate-service:{{.Values.image.tagInterestRateService}}
        imagePullPolicy: {{.Values.image.pullPolicy}}
        name: interest-rate-service
        ports:
        - containerPort: 8083
          protocol: TCP
        env:
       #DATABASE
        - name: DB_HOST_PORT
          valueFrom:
            configMapKeyRef:
              name: lease-a-car-api-configmap
              key: db-host-port
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: lease-a-car-api-secret
              key: db-user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: lease-a-car-api-secret
              key: db-password
        # SPRING
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            configMapKeyRef:
              name: lease-a-car-api-configmap
              key: spring-profiles-active
        livenessProbe:
          httpGet:  
            path: interest-rate-service/actuator/health/liveness
            port: 8083  
          initialDelaySeconds: 60 
          periodSeconds: 5
          failureThreshold: 10 
        readinessProbe:  
          httpGet:  
            path: interest-rate-service/actuator/health/readiness
            port: 8083  
          initialDelaySeconds: 60
          periodSeconds: 5
          failureThreshold: 10
---
apiVersion: v1
kind: Service
metadata:
  labels:
    api: lease-a-car-api
    service: interest-rate-service
  name: interest-rate-service
  namespace: default
spec:
  ports:
  - name: "8083"
    port: 8083
    targetPort: 8083
    protocol: TCP
  selector:
    service: interest-rate-service
  type: {{.Values.service.spec.type}}