apiVersion: v1
kind: Secret
metadata:
  name: lease-a-car-api-secret
  namespace: {{.Values.metadata.namespace}}
  labels:
    app: lease-a-car-api
  annotations:
    "helm.sh/hook": "pre-install"
type: Opaque
data:
  db-user: cm9vdA==
  db-password: bWFyaWFkYg==