apiVersion: v1
kind: ConfigMap
metadata:
  name: lease-a-car-api-configmap
  namespace: {{.Values.metadata.namespace}}
  labels:
    app: lease-a-car-api
  annotations:
    "helm.sh/hook": "pre-install"
data:
  spring-profiles-active: "postgres"
  db-host-port: "192.168.1.20:30116"