# Default values for k8s-helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

metadata:
  namespace: "default"

replicaCount: 1

image:
  repository: "hakktastic"
  pullPolicy: Always
  tag: "0.1.0"
  
service:
  spec:
    type: NodePort