# Default values for k8s-helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

metadata:
  namespace: "default"

replicaCount: 1

image:
  repository: "hakktastic"
  pullPolicy: Always
  tag-car-service: "0.6.1"
  tag-customer-service: "0.6.0"
  tag-interest-rate-service: "0.6.0"
  tag-lease-calculation-service: "0.6.0"
  
service:
  spec:
    type: NodePort